defaults:
  - _self_
  - problem: tsp_gls
  - llm_client: openai
  - override hydra/output: local

hydra:
  job:
    name: ${problem.problem_name}-${problem.problem_type}
    chdir: True

# The chosen algorithm
algorithm: hercules 

# Main GA loop parameters
max_fe: 100 # maximum number of function evaluations
pop_size: 10 # population size for GA
init_pop_size: 30 # initial population size for GA
mutation_rate: 0.5 # mutation rate for GA
timeout: 200 # timeout for evaluation of a single heuristic
diversify_init_pop: True # whether to diversify the initial population